#!/usr/bin/env bash

source jopa

save_function() {
  local orig_func=$(declare -f $1)
  local newname_func="$2${orig_func#$1}"
  eval "$newname_func"
}

save_function read_page _read_page

# drop N- prefix from target names used to keep order
read_page() {
  _read_page $1
  target="${target#*-}"
}

jopa
