name: Build pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: alpine-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: apk add --no-cache bash gettext
      - name: Build docs
        run: bash my-jopa
